#!/bin/bash

aws s3 cp s3://liyahe-test-lake/libraries/delta-core_2.12-1.0.0.jar /usr/lib/spark/jars/



df = spark.read.format("delta").load("/home/hadoop/delta-tb01")
df.show()


deltaTable = DeltaTable.forPath(spark，"/home/hadoop/delta-tb01"）




df = spark.read.format("delta").load("/tmp/delta-table")



df2 = spark.read.load("s3://liyahe-test-lake/delta_lake_storage/source/new_york_taxi/yellow_taxi/*.csv", format="csv", sep=",", inferSchema="true", header="true")



s3://liyahe-test-lake/delta_lake_storage/source/new_york_taxi/yellow_taxi/yellow_tripdata_2020-05.csv



deltaTable = DeltaTable.forPath("s3://liyahe-test-lake/delta_lake_storage/new_york_taxi/yellow_taxi/")
deltaTable.generate("symlink_format_manifest")
